[package]
name = "sentry_stripping_derive"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
quote = "0.6.3"
syn = "0.14.4"
synstructure = "0.9.0"
proc-macro2 = "0.4.6"

[lib]
proc-macro = true
